apiVersion: v1
kind: Pod
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: default

spec:
  containers:
    - name: keycloak
      image: "quay.io/keycloak/keycloak:26.3.1"
      imagePullPolicy: IfNotPresent
      ports:
        - hostPort: 8080
          containerPort: 8080
      args: ["start-dev"]
      env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: admin
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: admin