app:
  title: Keycloak Desktop Client
  realm: kkdt
  keycloak:
    issuer: http://localhost:8080/realms/kkdt
    token: http://localhost:8080/realms/kkdt/protocol/openid-connect/token

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

spring:
  application:
    name: Keycloak Desktop Client
  security:
    oauth2:
      client:
        provider:
          kkdt:
            issuer-uri: http://localhost:8080/realms/kkdt
            token-uri: http://localhost:8080/realms/kkdt/protocol/openid-connect/token
        registration:
          kkdt:
            provider: kkdt
            client-name: apps
            client-id: apps
            client-secret: E57lksP4Xo9LfmFWXmHcVIKXF1eER0dK
            scope: openid,offline_access,profile
            authorization-grant-type: authorization_code
